<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="com.atmecs.services.test.TestCurrencyWS" duration-ms="2061" started-at="2015-02-17T10:14:22Z" finished-at="2015-02-17T10:14:24Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="2061" started-at="2015-02-17T10:14:22Z" finished-at="2015-02-17T10:14:24Z">
      <class name="com.atmecs.services.test.TestCurrencyWS">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.atmecs.services.test.TestCurrencyWS@73f792cf]" name="setUp" is-config="true" duration-ms="672" started-at="2015-02-17T15:44:22Z" finished-at="2015-02-17T15:44:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testCurrencyRate()[pri:0, instance:com.atmecs.services.test.TestCurrencyWS@73f792cf]" name="testCurrencyRate" duration-ms="1373" started-at="2015-02-17T15:44:22Z" finished-at="2015-02-17T15:44:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [62.215] but found [62.2299]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [62.215] but found [62.2299]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.atmecs.services.test.TestCurrencyWS.testCurrencyRate(TestCurrencyWS.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCurrencyRate -->
        <test-method status="PASS" signature="open()[pri:0, instance:com.atmecs.services.test.TestCurrencyWS@73f792cf]" name="open" is-config="true" duration-ms="0" started-at="2015-02-17T15:44:22Z" finished-at="2015-02-17T15:44:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.atmecs.services.test.TestCurrencyWS@73f792cf]" name="close" is-config="true" duration-ms="0" started-at="2015-02-17T15:44:24Z" finished-at="2015-02-17T15:44:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.atmecs.services.test.TestCurrencyWS -->
    </test> <!-- Command line test -->
  </suite> <!-- com.atmecs.services.test.TestCurrencyWS -->
</testng-results>
